"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: Go2DDSMsgs
  IDL file: DDSMsgs.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import Go2DDSMsgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class PointCloud(idl.IdlStruct, typename="Go2DDSMsgs.PointCloud"):
    x: types.sequence[types.float32]
    y: types.sequence[types.float32]
    z: types.sequence[types.float32]
    timestamp: str


@dataclass
@annotate.final
@annotate.autoid("sequential")
class DepthImage(idl.IdlStruct, typename="Go2DDSMsgs.DepthImage"):
    width: types.uint16
    height: types.uint16
    data: types.sequence[types.uint16]
    timestamp: str


@dataclass
@annotate.final
@annotate.autoid("sequential")
class RGBImage(idl.IdlStruct, typename="Go2DDSMsgs.RGBImage"):
    width: types.uint16
    height: types.uint16
    data: types.sequence[types.uint8]
    timestamp: str


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Pose(idl.IdlStruct, typename="Go2DDSMsgs.Pose"):
    quat: types.array[types.float64, 4]
    trans: types.array[types.float64, 3]
    timestamp: str


@dataclass
@annotate.final
@annotate.autoid("sequential")
class HighCommand(idl.IdlStruct, typename="Go2DDSMsgs.HighCommand"):
    vx: types.float64
    vy: types.float64
    omega: types.float64
    timestamp: str


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Imu(idl.IdlStruct, typename="Go2DDSMsgs.Imu"):
    accel: types.array[types.float64, 3]
    gyro: types.array[types.float64, 3]
    quat: types.array[types.float64, 4]
    timestamp: str


